import { fileURLToPath } from 'node:url';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig, type Plugin } from 'vitest/config';

/** SvelteKit's own `$lib`, which only exists inside the Kit pipeline. */
const libAlias = { $lib: fileURLToPath(new URL('./src/lib', import.meta.url)) };

/**
 * `$app/environment` and `$env/dynamic/public` are generated by SvelteKit at
 * build time, so a test run outside the Kit pipeline cannot resolve them.
 * Serving them as virtual modules keeps the auth module importable without a
 * pair of stub files sitting next to real source.
 *
 * `convexUrl` is a parameter because it is what decides which of the two modes
 * a module under test comes up in: the auth module needs a deployment to talk
 * to, while the store's local mode is defined by there being none.
 */
const svelteKitStubs = (convexUrl: string): Plugin => ({
  name: 'sveltekit-env-stubs',
  resolveId(id) {
    if (id === '$app/environment' || id === '$env/dynamic/public') return `\0${id}`;
    return null;
  },
  load(id) {
    if (id === '\0$app/environment') return 'export const browser = true;';
    if (id === '\0$env/dynamic/public') {
      return `export const env = { PUBLIC_CONVEX_URL: ${JSON.stringify(convexUrl)} };`;
    }
    return null;
  }
});

export default defineConfig({
  test: {
    projects: [
      {
        // Pure TypeScript modules — no Convex runtime and no Svelte compiler
        // needed. `src/lib/components` is in here for the plain `.ts` files
        // that sit beside components: the seed-import payload builder is
        // logic a component calls, not a component, and it is worth testing
        // precisely because the mutation it feeds cannot be exercised here.
        // The `$lib` alias is needed because those tests import the dataset.
        resolve: { alias: libAlias },
        test: {
          name: 'unit',
          include: [
            'src/lib/finance/**/*.test.ts',
            'src/lib/components/**/*.test.ts',
            'scripts/import/**/*.test.ts'
          ],
          environment: 'node'
        }
      },
      {
        // Convex functions run against convex-test's in-memory backend.
        test: {
          name: 'convex',
          include: ['convex/**/*.test.ts'],
          environment: 'edge-runtime',
          server: { deps: { inline: ['convex-test'] } }
        }
      },
      {
        // The auth module is a `.svelte.ts` file, so it needs the Svelte
        // compiler to turn its runes into real reactive state.
        plugins: [svelteKitStubs('https://test-deployment.convex.cloud'), svelte()],
        test: {
          name: 'auth',
          include: ['src/lib/auth/**/*.test.ts'],
          environment: 'node'
        }
      },
      {
        // The store, likewise a `.svelte.ts` file. Deliberately given no
        // `PUBLIC_CONVEX_URL`, so it comes up in local mode: opening a live
        // websocket to a deployment that does not exist is not something a
        // unit test should do, and every behaviour asserted here (the
        // migration purge, the season filters) is client-side arithmetic.
        plugins: [svelteKitStubs(''), svelte()],
        resolve: { alias: libAlias },
        test: {
          name: 'store',
          include: ['src/lib/stores/**/*.test.ts'],
          environment: 'node'
        }
      }
    ]
  }
});
